apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  annotations:
#    meta.helm.sh/release-name: {{ .Release.Name }}
#    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: mysql-pv-claim
  labels:
    app: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
