---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: 1Gi
