# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: quay.io/umangachapagain
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: true

ocCreateRoute: true

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart: {}

catalogue: {}

dispatch: {}

mongodb:
  # Storage class and size to use with mongodb PVC
  storageClassName: ocs-storagecluster-ceph-rbd
  storage: 1Gi

mysql:
  # Storage class and size to use with mysql PVC
  storageClassName: ocs-storagecluster-ceph-rbd
  storage: 1Gi

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq: {}

ratings: {}

redis:
  # Storage class and size to use with redis PVC
  storageClassName: ocs-storagecluster-ceph-rbd
  storage: 1Gi

shipping: {}

user: {}

web: {}
